# data settings
data_type: 'raw'
data_dir: 'VRNN-generation/data/camrest'
domain: 'camrest'
#data_dir: 'VRNN-generation/data/smd'
#domain: 'smd'
#data_dir: 'VRNN-generation/data/multiwoz'
#domain: 'woz-hotel'
#data_dir: 'VRNN-generation/data/daily'
#domain: 'daily'
#db_file: 'VRNN-generation/data/multiwoz/db.json'
db_file: 'VRNN-generation/data/camrest/db.json'
embedding_fn: 'VRNN-generation/data/embeddings/fasttext-wiki.vec'
embedding_out_fn: 'VRNN-generation/data/embeddings/fasttext-wiki.pkl'
# general settings
max_allowed_turn_len: 20
delex: true
device_name: 'cpu:0' # cpu|cuda
activation: 'tanh'
batch_size: 4
quantization: 0.1
drop_prob: 0.3
lr_decay_rate: 0.98
init_gumbel_softmax_tmp: 2.0
gumbel_softmax_tmp: 2.0
teacher_forcing_prob: 0.3
z_teacher_forcing_prob: 0.3
kl_to_ce: 1
user_number_z_vectors: 1
system_number_z_vectors: 5
begin_kl_opt_epoch: 1
stop_opt_z: 20
prior_module_recurrent: false
gumbel_hard: false
bidirectional_encoder: true
use_db_api: false
use_copynet: false
use_attention: true
#use_copynet: false
#use_attention: false
with_bpr: false
with_bow_loss: false
fake_prior: false
min_epochs: 80
max_epochs: 100
db_cutoff: 3
copy_start_epoch: 5
# KL before start increasing
init_KL_term: 0.001
# bow loss setting
k_loss_coeff: 0.1
alpha_coeff_step: 0.5
default_lambda_loss: 1.0
# layer sizes
input_encoder_hidden_size: 250
user_decoder_hidden_size: 250
system_decoder_hidden_size: 350
vrnn_hidden_size: 100
posterior_ff_sizes1:
  - 100
#  - 200
posterior_ff_sizes2:
#  - 200
  - 100
prior_lstm_size: 150
prior_ff_sizes:
  - 100
bow_layer_size: 400
# latent z config
user_z_type: 'cont' # cont| gumbel;
system_z_type: 'gumbel'
user_z_logits_dim: 200
system_z_logits_dim: 20
