# data settings
data_type: 'raw'
data_dir: 'VRNN/data/camrest'
domain: 'camrest'
#data_dir: 'VRNN/data/woz-hotel'
#domain: 'woz-hotel'
embedding_fn: 'VRNN/data/embeddings/fasttext-wiki.pkl'
# general settings
batch_size: 8
drop_prob: 0.5
bidirectional_encoder: true
gumbel_softmax_tmp: 5
teacher_forcing_prob: 0.5
number_z_vectors: 3
with_bow_loss: false
k_loss_coeff: 0.1
init_KL_term: 0.001
alpha_coeff_step: 0.5
default_lambda_loss: 1.0
with_BPR: false
user_z_type: 'cont' # cont| gumbel;
system_z_type: 'gumbel'
# layer sizes
input_encoder_hidden_size: 150
decoder_hidden_size: 300
vrnn_hidden_size: 200
posterior_ff_sizes1:
  - 200
#  - 200
posterior_ff_sizes2:
#  - 200
  - 200
prior_ff_sizes:
  - 100
  - 100
user_z_logits_dim: 150
system_z_logits_dim: 20
bow_layer_size: 400