# data settings
data_type: 'raw'
data_dir: 'VRNN/data/camrest'
domain: 'camrest'
#data_dir: 'VRNN/data/woz-hotel'
#domain: 'woz-hotel'
embedding_fn: 'VRNN/data/embeddings/fasttext-wiki.pkl'
# general settings
batch_size: 8
drop_prob: 0.65
lr_decay_rate: 0.98
bidirectional_encoder: true
gumbel_softmax_tmp: 1.0
teacher_forcing_prob: 0.5
number_z_vectors: 3
with_bpr: false
with_bow_loss: false
begin_kl_opt_epoch: 1
fake_prior: true
min_epochs: 50
max_epochs: 100

# KL before start increasing
init_KL_term: 0.001
# bow loss setting
k_loss_coeff: 0.1
alpha_coeff_step: 0.5
default_lambda_loss: 1.0
# layer sizes
input_encoder_hidden_size: 150
user_decoder_hidden_size: 200
system_decoder_hidden_size: 200
vrnn_hidden_size: 150
posterior_ff_sizes1:
  - 200
#  - 200
posterior_ff_sizes2:
#  - 200
  - 200
prior_ff_sizes:
  - 250
  - 150
bow_layer_size: 400
# latent z config
user_z_type: 'cont' # cont| gumbel;
system_z_type: 'gumbel'
user_z_logits_dim: 150
system_z_logits_dim: 20
