# data settings
data_type: 'raw'
data_dir: 'VRNN/data/camrest'
domain: 'camrest'
#data_dir: 'VRNN/data/woz-hotel'
#domain: 'woz-hotel'
embedding_fn: 'VRNN/data/embeddings/fasttext-wiki.vec'
# general settings
batch_size: 8
drop_prob: 0.7
lr_decay_rate: 0.98
gumbel_softmax_tmp: 2.0
teacher_forcing_prob: 0.5
z_teacher_forcing_prob: 0.5
kl_to_ce: 1
number_z_vectors: 5
begin_kl_opt_epoch: 3
prior_module_recurrent: false
gumbel_hard: false
bidirectional_encoder: true
use_copynet: true
use_attention: true
with_bpr: false
with_bow_loss: false
fake_prior: false
min_epochs: 90
max_epochs: 100
db_cutoff: 3

# KL before start increasing
init_KL_term: 0.001
# bow loss setting
k_loss_coeff: 0.1
alpha_coeff_step: 0.5
default_lambda_loss: 1.0
# layer sizes
input_encoder_hidden_size: 200
user_decoder_hidden_size: 200
system_decoder_hidden_size: 250
vrnn_hidden_size: 250
posterior_ff_sizes1:
  - 200
#  - 200
posterior_ff_sizes2:
#  - 200
  - 200
prior_lstm_size: 150
prior_ff_sizes:
  - 120
  - 50
bow_layer_size: 400
# latent z config
user_z_type: 'cont' # cont| gumbel;
system_z_type: 'gumbel'
user_z_logits_dim: 150
system_z_logits_dim: 20
