# data settings
data_type: 'raw'
data_fn: 'VRNN/data/CamRest676.json'
domain: 'camrest'
embedding_fn: 'VRNN/data/embeddings/fasttext-wiki.pkl'
# general settings
batch_size: 16
drop_prob: 0.5
bidirectional_encoder: true
gumbel_softmax_tmp: 0.8
teacher_forcing_prob: 0.5
# layer sizes
input_encoder_hidden_size: 100
decoder_hidden_size: 200
vrnn_hidden_size: 200
posterior_ff_sizes1:
  - 400
  - 200
posterior_ff_sizes2:
  - 200
  - 200
prior_ff_sizes:
  - 100
  - 100
z_logits_dim: 50